%
%  Ex_OFI_DoubleLunarSwingby
%
%  Script Mission - Double Lunar Swingby Example
%
%  This script demonstrates how to set up a double Lunar swingby with
%  multiple targeting sequences.
%
%  Released: R2020a
%


%--------------------------------------------------------------------------
%----------------- SpaceCraft, Formations, Constellations -----------------
%--------------------------------------------------------------------------

Create Spacecraft MMSRef;

MMSRef.DateFormat       = UTCGregorian;
MMSRef.Epoch            = '24 May 2014 15:17:21.927';
MMSRef.CoordinateSystem = EarthMJ2000Eq;
MMSRef.DisplayStateType = Keplerian;
MMSRef.SMA              = 83230.75058999992;
MMSRef.ECC              = 0.89643283;
MMSRef.INC              = 15.50000000000001;
MMSRef.RAAN             = 15.96879432999999;
MMSRef.AOP              = 289.7205240999998;
MMSRef.TA               = 179.9999987925817;
MMSRef.DryMass          = 400;
MMSRef.Cd               = 2.2;
MMSRef.Cr               = 1.7;
MMSRef.DragArea         = 5;
MMSRef.SRPArea          = 5;

%--------------------------------------------------------------------------
%------------------------------ Force Models ------------------------------
%--------------------------------------------------------------------------

Create ForceModel LunarSB_ForceModel;

LunarSB_ForceModel.CentralBody            = Earth;
LunarSB_ForceModel.PointMasses            = {Earth, Sun, Luna};
LunarSB_ForceModel.Drag                   = None;
LunarSB_ForceModel.SRP                    = Off;
LunarSB_ForceModel.RelativisticCorrection = Off;
LunarSB_ForceModel.ErrorControl           = RSSStep;

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator LunarSB;

LunarSB.FM              = LunarSB_ForceModel;
LunarSB.Type            = RungeKutta89;
LunarSB.InitialStepSize = 60;
LunarSB.Accuracy        = 1e-011;
LunarSB.MinStep         = 0.001;
LunarSB.MaxStep         = 30000;
LunarSB.MaxStepAttempts = 50;
LunarSB.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn TOI;

TOI.CoordinateSystem   = Local;
TOI.Origin             = Earth;
TOI.Axes               = VNB;
TOI.Element1           = 0.01;
TOI.Element2           = 0;
TOI.Element3           = 0;
TOI.DecrementMass      = false;
TOI.Isp                = 300;
TOI.GravitationalAccel = 9.810000000000001;

Create ImpulsiveBurn LST;

LST.CoordinateSystem   = Local;
LST.Origin             = Earth;
LST.Axes               = VNB;
LST.Element1           = 0;
LST.Element2           = 0;
LST.Element3           = 0;
LST.DecrementMass      = false;
LST.Isp                = 300;
LST.GravitationalAccel = 9.810000000000001;

Create ImpulsiveBurn ALM;

ALM.CoordinateSystem   = Local;
ALM.Origin             = Earth;
ALM.Axes               = VNB;
ALM.Element1           = -0.354;
ALM.Element2           = 0;
ALM.Element3           = 0;
ALM.DecrementMass      = false;
ALM.Isp                = 300;
ALM.GravitationalAccel = 9.810000000000001;

Create ImpulsiveBurn LunarPhasedV;

LunarPhasedV.CoordinateSystem   = Local;
LunarPhasedV.Origin             = Earth;
LunarPhasedV.Axes               = VNB;
LunarPhasedV.Element1           = 0.027;
LunarPhasedV.Element2           = 0;
LunarPhasedV.Element3           = 0;
LunarPhasedV.DecrementMass      = false;
LunarPhasedV.Isp                = 300;
LunarPhasedV.GravitationalAccel = 9.810000000000001;

%----------------------------------------
%---------- Coordinate Systems
%----------------------------------------

Create CoordinateSystem EarthSunRot;

EarthSunRot.Origin    = Earth;
EarthSunRot.Axes      = ObjectReferenced;
EarthSunRot.XAxis     = R;
EarthSunRot.ZAxis     = N;
EarthSunRot.Primary   = Sun;
EarthSunRot.Secondary = Earth;

Create CoordinateSystem MoonMJ2000Eq;

MoonMJ2000Eq.Origin   = Luna;
MoonMJ2000Eq.Axes     = MJ2000Eq;

Create CoordinateSystem EarthMoonRot;

EarthMoonRot.Origin    = Luna;
EarthMoonRot.Axes      = ObjectReferenced;
EarthMoonRot.XAxis     = R;
EarthMoonRot.ZAxis     = N;
EarthMoonRot.Primary   = Earth;
EarthMoonRot.Secondary = Luna;

Create CoordinateSystem GSE;

GSE.Origin             = Earth;
GSE.Axes               = ObjectReferenced;
GSE.XAxis              = R;
GSE.ZAxis              = N;
GSE.Primary            = Sun;
GSE.Secondary          = Earth;

%----------------------------------------
%---------- Solvers
%----------------------------------------

Create DifferentialCorrector DC1;

DC1.ShowProgress      = true;
DC1.ReportStyle       = Normal;
DC1.ReportFile        = 'DifferentialCorrectorDC1.data';
DC1.MaximumIterations = 10;
DC1.DerivativeMethod  = ForwardDifference;
DC1.Algorithm         = NewtonRaphson;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create XYPlot EarthDistance;

EarthDistance.SolverIterations = None;
EarthDistance.UpperLeft        = [ 0.3 0.03 ];
EarthDistance.Size             = [ 0.34 0.45 ];
EarthDistance.RelativeZOrder   = 135;
EarthDistance.Maximized        = true;
EarthDistance.XVariable        = MMSRef.A1ModJulian;
EarthDistance.YVariables       = {MMSRef.Earth.RMAG};
EarthDistance.ShowGrid         = true;
EarthDistance.ShowPlot         = true;


Create OpenFramesInterface OFI_EarthMJ2K;

OFI_EarthMJ2K.SolverIterations = All;
OFI_EarthMJ2K.UpperLeft        = [ 0.3 0.48 ];
OFI_EarthMJ2K.Size             = [ 0.34 0.45 ];
OFI_EarthMJ2K.RelativeZOrder   = 148;
OFI_EarthMJ2K.Maximized        = false;
OFI_EarthMJ2K.Add              = {MMSRef, Earth, Luna, Sun};
OFI_EarthMJ2K.View             = {CoordinateSystemView1};
OFI_EarthMJ2K.CoordinateSystem = EarthMJ2000Eq;
OFI_EarthMJ2K.DrawObject       = [ true true true true ];

Create OpenFramesInterface OFI_EarthMoonRot;

OFI_EarthMoonRot.SolverIterations = Current;
OFI_EarthMoonRot.UpperLeft        = [ 0.65 0.48 ];
OFI_EarthMoonRot.Size             = [ 0.34 0.45 ];
OFI_EarthMoonRot.RelativeZOrder   = 126;
OFI_EarthMoonRot.Maximized        = true;
OFI_EarthMoonRot.Add              = {MMSRef, Earth, Luna, Sun};
OFI_EarthMoonRot.View             = {CoordinateSystemView2};
OFI_EarthMoonRot.CoordinateSystem = EarthMoonRot;
OFI_EarthMoonRot.DrawObject       = [ true true true true ];

Create OpenFramesInterface OFI_EarthGSE;

OFI_EarthGSE.SolverIterations     = Current;
OFI_EarthGSE.UpperLeft            = [ 0.65 0.03 ];
OFI_EarthGSE.Size                 = [ 0.34 0.45 ];
OFI_EarthGSE.RelativeZOrder       = 127;
OFI_EarthGSE.Maximized            = true;
OFI_EarthGSE.Add                  = {MMSRef, Earth, Luna, Sun};
OFI_EarthGSE.View                 = {CoordinateSystemView3};
OFI_EarthGSE.CoordinateSystem     = GSE;
OFI_EarthGSE.DrawObject           = [ true true true true ];

%----------------------------------------
%---------- View Objects
%----------------------------------------

Create OpenFramesView CoordinateSystemView1;

CoordinateSystemView1.ViewFrame          = CoordinateSystem;
CoordinateSystemView1.ViewTrajectory     = Off;
CoordinateSystemView1.InertialFrame      = Off;
CoordinateSystemView1.SetDefaultLocation = Off;
CoordinateSystemView1.SetCurrentLocation = On;
CoordinateSystemView1.CurrentEye         = [ -18000 -85000 1650000 ];
CoordinateSystemView1.CurrentCenter      = [ 0 0 0 ];
CoordinateSystemView1.CurrentUp          = [ 0 1 0 ];

Create OpenFramesView CoordinateSystemView2;

CoordinateSystemView2.ViewFrame          = CoordinateSystem;
CoordinateSystemView2.ViewTrajectory     = Off;
CoordinateSystemView2.InertialFrame      = Off;
CoordinateSystemView2.SetDefaultLocation = Off;
CoordinateSystemView2.SetCurrentLocation = On;
CoordinateSystemView2.CurrentEye         = [ 50000 -240000 2250000 ];
CoordinateSystemView2.CurrentCenter      = [ 0 0 0 ];
CoordinateSystemView2.CurrentUp          = [ 0 1 0 ];

Create OpenFramesView CoordinateSystemView3;

CoordinateSystemView3.ViewFrame          = CoordinateSystem;
CoordinateSystemView3.ViewTrajectory     = Off;
CoordinateSystemView3.InertialFrame      = Off;
CoordinateSystemView3.SetDefaultLocation = Off;
CoordinateSystemView3.SetCurrentLocation = On;
CoordinateSystemView3.CurrentEye         = [ -200000 -75000 1500000 ];
CoordinateSystemView3.CurrentCenter      = [ 0 0 0 ];
CoordinateSystemView3.CurrentUp          = [ 0 1 0 ];

%----------------------------------------
%---------- Arrays, Variables, Strings
%----------------------------------------
Create Variable I;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
BeginMissionSequence;

BeginScript
   Toggle OFI_EarthMoonRot Off;
   Toggle OFI_EarthMJ2K    Off;
   Toggle OFI_EarthGSE     Off;
   Toggle OFI_EarthMoonRot On;
   Toggle OFI_EarthMJ2K    On;
   Toggle OFI_EarthGSE     On;
EndScript;

%------------------------------
%  Waiting Loops
%------------------------------
For 'For I = 1:14' I = 1:1:14;
   Propagate 'Prop to Periapsis' LunarSB(MMSRef) {MMSRef.Periapsis};
EndFor;

%------------------------------
%  Phasing Loops
%------------------------------
For 'For I = 1:5' I = 1:1:5;
   Propagate 'Prop to Periapsis' LunarSB(MMSRef) {MMSRef.Periapsis};
   Maneuver 'Apply LunarPhasedV' LunarPhasedV(MMSRef);
EndFor;

%%------------------------------
%%  Prop to periapsis for LSI
%%------------------------------
Maneuver 'Apply TOI' TOI(MMSRef);
Propagate 'Prop to Apogee' LunarSB(MMSRef) {MMSRef.Apoapsis};

%------------------------------
%  Target Lunar B-plane
%------------------------------
Target 'Target Flyby' DC1 {SolveMode  = Solve, ExitMode = DiscardAndContinue, ShowProgressWindow = true};
   Vary 'Vary LST.N' DC1(LST.Element2 = 0.03413111106956, {Perturbation = 1e-005, Lower = -.5, Upper = .5, MaxStep = .02, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Vary 'Vary LST.B' DC1(LST.Element3 = -0.09078959728280001, {Perturbation = 1e-004, Lower = -.5, Upper = .5, MaxStep = .01, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Maneuver 'Apply LST' LST(MMSRef);
   Propagate 'Prop to Periselene' LunarSB(MMSRef) {MMSRef.Luna.Periapsis};
   Achieve 'Achieve BdotT' DC1(MMSRef.MoonMJ2000Eq.BdotT = 150000, {Tolerance = .001});
   Achieve 'Acheive BdotR' DC1(MMSRef.MoonMJ2000Eq.BdotR = -10000, {Tolerance = .001});
EndTarget;  % For targeter DC1


%%------------------------------
%% Propagate to Earth Periapsis
%%------------------------------
Propagate 'Prop to Perigee' LunarSB(MMSRef) {MMSRef.Periapsis};

%------------------------------
% Target to lower Apogee
%------------------------------
Target 'Lower Apogee' DC1 {SolveMode = Solve, ExitMode = DiscardAndContinue, ShowProgressWindow = true};
   Vary 'Vary ALM.V' DC1(ALM.Element1 = -0.3198120104, {Perturbation = 1e-006, Lower = -.5, Upper = .5, MaxStep = .08, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Maneuver 'Apply ALM' ALM(MMSRef);
   Achieve 'Achieve RadApo' DC1(MMSRef.Earth.RadApo = 191344.0, {Tolerance = .00001});
EndTarget;  % For targeter DC1

Propagate LunarSB(MMSRef) {MMSRef.ElapsedDays = 10};
