%
%  Ex_OFI_ElectricPropulsion
%
%  Use a long low-thrust burn using an electric thruster.
%
%  Released: R2020a
%


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;

DefaultSC.DateFormat       = UTCGregorian;
DefaultSC.Epoch            = '15 Dec 2017 14:56:42.200';
DefaultSC.CoordinateSystem = EarthMJ2000Eq;
DefaultSC.DisplayStateType = Cartesian;
DefaultSC.X                = -15015.40312811781;
DefaultSC.Y                = -23568.97680091111;
DefaultSC.Z                = 2241.504923500546;
DefaultSC.VX               = -0.485537892208224;
DefaultSC.VY               = -5.048763191594085;
DefaultSC.VZ               = -0.8799883161637991;
DefaultSC.DryMass          = 7;
DefaultSC.Cd               = 2.2;
DefaultSC.Cr               = 1.8;
DefaultSC.DragArea         = 15;
DefaultSC.SRPArea          = 1;
DefaultSC.Tanks            = {ElectricTank1};
DefaultSC.Thrusters        = {ElectricThruster1};
DefaultSC.PowerSystem      = SolarPowerSystem1;

%----------------------------------------
%---------- Hardware Components
%----------------------------------------

Create ElectricTank ElectricTank1;

ElectricTank1.AllowNegativeFuelMass = false;
ElectricTank1.FuelMass              = 5;

Create ElectricThruster ElectricThruster1;

ElectricThruster1.CoordinateSystem   = Local;
ElectricThruster1.Origin             = Earth;
ElectricThruster1.Axes               = VNB;
ElectricThruster1.ThrustDirection1   = -1;
ElectricThruster1.ThrustDirection2   = 0;
ElectricThruster1.ThrustDirection3   = 0;
ElectricThruster1.DutyCycle          = 1;
ElectricThruster1.ThrustScaleFactor  = 0.9;
ElectricThruster1.DecrementMass      = false;
ElectricThruster1.Tank               = {ElectricTank1};
ElectricThruster1.MixRatio           = [1];
ElectricThruster1.GravitationalAccel = 9.810000000000001;
ElectricThruster1.ThrustModel        = ConstantThrustAndIsp;
ElectricThruster1.MaximumUsablePower = 7.266;
ElectricThruster1.MinimumUsablePower = 0.01;
ElectricThruster1.ThrustCoeff1       = -5.19082;
ElectricThruster1.ThrustCoeff2       = 2.96519;
ElectricThruster1.ThrustCoeff3       = -14.4789;
ElectricThruster1.ThrustCoeff4       = 54.05382;
ElectricThruster1.ThrustCoeff5       = -0.00100092;
ElectricThruster1.MassFlowCoeff1     = -0.004776;
ElectricThruster1.MassFlowCoeff2     = 0.05717;
ElectricThruster1.MassFlowCoeff3     = -0.09956;
ElectricThruster1.MassFlowCoeff4     = 0.03211;
ElectricThruster1.MassFlowCoeff5     = 2.13781;
ElectricThruster1.FixedEfficiency    = 0.7;
ElectricThruster1.Isp                = 2800;
ElectricThruster1.ConstantThrust     = 0.0012;

Create SolarPowerSystem SolarPowerSystem1;

SolarPowerSystem1.EpochFormat        = 'UTCGregorian';
SolarPowerSystem1.InitialEpoch       = ''01 Jan 2000 11:59:28.000'';
SolarPowerSystem1.InitialMaxPower    = 1.2;
SolarPowerSystem1.AnnualDecayRate    = 5;
SolarPowerSystem1.Margin             = 5;
SolarPowerSystem1.BusCoeff1          = 0.3;
SolarPowerSystem1.BusCoeff2          = 0;
SolarPowerSystem1.BusCoeff3          = 0;
SolarPowerSystem1.ShadowModel        = 'DualCone';
SolarPowerSystem1.ShadowBodies       = {'Luna'};
SolarPowerSystem1.SolarCoeff1        = 1.32077;
SolarPowerSystem1.SolarCoeff2        = -0.10848;
SolarPowerSystem1.SolarCoeff3        = -0.11665;
SolarPowerSystem1.SolarCoeff4        = 0.10843;
SolarPowerSystem1.SolarCoeff5        = -0.01279;

%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;

DefaultProp_ForceModel.CentralBody            = Luna;
DefaultProp_ForceModel.PointMasses            = {Earth, Luna, Sun};
DefaultProp_ForceModel.Drag                   = None;
DefaultProp_ForceModel.SRP                    = Off;
DefaultProp_ForceModel.RelativisticCorrection = Off;
DefaultProp_ForceModel.ErrorControl           = RSSStep;

Create ForceModel LunarProp_ForceModel;

LunarProp_ForceModel.CentralBody                     = Luna;
LunarProp_ForceModel.PrimaryBodies                   = {Luna};
LunarProp_ForceModel.PointMasses                     = {Earth, Sun};
LunarProp_ForceModel.Drag                            = None;
LunarProp_ForceModel.SRP                             = Off;
LunarProp_ForceModel.RelativisticCorrection          = Off;
LunarProp_ForceModel.ErrorControl                    = RSSStep;
LunarProp_ForceModel.GravityField.Luna.Degree        = 4;
LunarProp_ForceModel.GravityField.Luna.Order         = 4;
LunarProp_ForceModel.GravityField.Luna.PotentialFile = 'LP165P.cof';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;

DefaultProp.FM                       = DefaultProp_ForceModel;
DefaultProp.Type                     = RungeKutta89;
DefaultProp.InitialStepSize          = 60;
DefaultProp.Accuracy                 = 9.999999999999999e-012;
DefaultProp.MinStep                  = 0.001;
DefaultProp.MaxStep                  = 86400;
DefaultProp.MaxStepAttempts          = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

Create Propagator LunarProp;

LunarProp.FM                       = LunarProp_ForceModel;
LunarProp.Type                     = RungeKutta89;
LunarProp.InitialStepSize          = 60;
LunarProp.Accuracy                 = 9.999999999999999e-012;
LunarProp.MinStep                  = 0.001;
LunarProp.MaxStep                  = 2700;
LunarProp.MaxStepAttempts          = 50;
LunarProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create FiniteBurn FiniteBurn1;

FiniteBurn1.Thrusters              = {ElectricThruster1};
FiniteBurn1.ThrottleLogicAlgorithm = 'MaxNumberOfThrusters';

%----------------------------------------
%---------- Coordinate Systems
%----------------------------------------

Create CoordinateSystem MoonJ2k;

MoonJ2k.Origin = Luna;
MoonJ2k.Axes   = MJ2000Eq;

Create CoordinateSystem CS_ESRotating;

CS_ESRotating.Origin    = Earth;
CS_ESRotating.Axes      = ObjectReferenced;
CS_ESRotating.XAxis     = -R;
CS_ESRotating.ZAxis     = N;
CS_ESRotating.Primary   = Earth;
CS_ESRotating.Secondary = Sun;

Create CoordinateSystem CS_EMRotating;

CS_EMRotating.Origin    = Earth;
CS_EMRotating.Axes      = ObjectReferenced;
CS_EMRotating.XAxis     = R;
CS_EMRotating.ZAxis     = N;
CS_EMRotating.Primary   = Earth;
CS_EMRotating.Secondary = Luna;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OpenFramesInterface MoonInertialView;

MoonInertialView.SolverIterations = Current;
MoonInertialView.UpperLeft        = [ 0.35 0.3 ];
MoonInertialView.Size             = [ 0.45 0.66 ];
MoonInertialView.RelativeZOrder   = 3;
MoonInertialView.Maximized        = false;
MoonInertialView.Add              = {DefaultSC, Luna, Sun, Earth};
MoonInertialView.View             = {MoonInertialViewCSView, DefaultSCView1};
MoonInertialView.CoordinateSystem = MoonJ2k;
MoonInertialView.DrawObject       = [ true true true true ];
MoonInertialView.DrawTrajectory   = [ true true true true ];

Create OpenFramesInterface EarthMoonRotatingView;

EarthMoonRotatingView.SolverIterations = Current;
EarthMoonRotatingView.UpperLeft        = [ 0.63 0 ];
EarthMoonRotatingView.Size             = [ 0.32 0.52 ];
EarthMoonRotatingView.RelativeZOrder   = 2;
EarthMoonRotatingView.Maximized        = false;
EarthMoonRotatingView.Add              = {DefaultSC, Earth, Sun, Luna};
EarthMoonRotatingView.CoordinateSystem = CS_EMRotating;
EarthMoonRotatingView.View             = {EarthMoonRotatingViewCSView};
EarthMoonRotatingView.DrawObject       = [ true true true true ];
EarthMoonRotatingView.DrawTrajectory   = [ true true true true ];

Create OpenFramesInterface EarthSunRotatingView;

EarthSunRotatingView.SolverIterations = Current;
EarthSunRotatingView.UpperLeft        = [ 0.25 0 ];
EarthSunRotatingView.Size             = [ 0.37 0.52 ];
EarthSunRotatingView.RelativeZOrder   = 1;
EarthSunRotatingView.Maximized        = true;
EarthSunRotatingView.Add              = {DefaultSC, Earth, Sun, Luna};
EarthSunRotatingView.View             = {EarthSunRotatingViewCSView};
EarthSunRotatingView.CoordinateSystem = CS_ESRotating;
EarthSunRotatingView.DrawObject       = [ true true true true ];
EarthSunRotatingView.DrawTrajectory   = [ true true true true ];

%----------------------------------------
%---------- View Objects
%----------------------------------------

Create OpenFramesView MoonInertialViewCSView;

MoonInertialViewCSView.ViewFrame          = CoordinateSystem;
MoonInertialViewCSView.ViewTrajectory     = Off;
MoonInertialViewCSView.InertialFrame      = Off;
MoonInertialViewCSView.SetDefaultLocation = Off;
MoonInertialViewCSView.SetCurrentLocation = On;
MoonInertialViewCSView.CurrentEye         = [ 0 0 50000 ];
MoonInertialViewCSView.CurrentCenter      = [ 0 0 0 ];
MoonInertialViewCSView.CurrentUp          = [ 1 0 0 ];

Create OpenFramesView DefaultSCView1;

DefaultSCView1.ViewFrame                  = DefaultSC;
DefaultSCView1.ViewTrajectory             = Off;
DefaultSCView1.InertialFrame              = Off;
DefaultSCView1.SetDefaultLocation         = Off;
DefaultSCView1.SetCurrentLocation         = Off;

Create OpenFramesView EarthMoonRotatingViewCSView;

EarthMoonRotatingViewCSView.ViewFrame          = CoordinateSystem;
EarthMoonRotatingViewCSView.ViewTrajectory     = Off;
EarthMoonRotatingViewCSView.InertialFrame      = Off;
EarthMoonRotatingViewCSView.SetDefaultLocation = Off;
EarthMoonRotatingViewCSView.SetCurrentLocation = On;
EarthMoonRotatingViewCSView.CurrentEye         = [ 0 0 1800000 ];
EarthMoonRotatingViewCSView.CurrentCenter      = [ 0 0 0 ];
EarthMoonRotatingViewCSView.CurrentUp          = [ 0 0 1 ];

Create OpenFramesView EarthSunRotatingViewCSView;

EarthSunRotatingViewCSView.ViewFrame           = CoordinateSystem;
EarthSunRotatingViewCSView.ViewTrajectory      = Off;
EarthSunRotatingViewCSView.InertialFrame       = Off;
EarthSunRotatingViewCSView.SetDefaultLocation  = Off;
EarthSunRotatingViewCSView.SetCurrentLocation  = On;
EarthSunRotatingViewCSView.CurrentEye          = [ 0 0 1500000 ];
EarthSunRotatingViewCSView.CurrentCenter       = [ 0 0 0 ];
EarthSunRotatingViewCSView.CurrentUp           = [ 0 0 1 ];

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
BeginMissionSequence;


Propagate 'Coast for 2 Hours' DefaultProp(DefaultSC) {DefaultSC.ElapsedSecs = 7200};
%  Turn on the electric propulsion system

BeginFiniteBurn FiniteBurn1(DefaultSC);
Propagate 'Prop Through Burn' DefaultProp(DefaultSC) {DefaultSC.ElapsedDays = 1.98, OrbitColor = Red};

%  Turn off the electric propulsion system
EndFiniteBurn FiniteBurn1(DefaultSC);
Propagate 'Lunar Periapsis' DefaultProp(DefaultSC) {DefaultSC.Luna.Periapsis, OrbitColor = Green};
Propagate 'Earth Apoapsis' DefaultProp(DefaultSC) {DefaultSC.Earth.Apoapsis, OrbitColor = Green};
Propagate 'Earth Periapsis' DefaultProp(DefaultSC) {DefaultSC.Earth.Periapsis, OrbitColor = Green};
Propagate 'Earth RMAG = 400000' DefaultProp(DefaultSC) {DefaultSC.Earth.RMAG = 400000, StopTolerance = 1e-05, OrbitColor = Green};
Propagate 'Earth Apoapsis' DefaultProp(DefaultSC) {DefaultSC.Earth.Apoapsis, OrbitColor = Green};




