%
%  Ex_OFI_RealTimeMOC
%
%  This script demonstrates using the OFI to display realtime data,
%  such as in a Mission Operations Center (MOC). The principles are
%  identical to those of standard OFI graphics.
%
%  Released: R2020a
%


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft theSat;

theSat.DateFormat                   = TAIModJulian;
theSat.Epoch                        = '21545';
theSat.CoordinateSystem             = EarthMJ2000Eq;
theSat.DisplayStateType             = ModifiedKeplerian;
theSat.RadPer                       = 8000.378524789952;
theSat.RadApo                       = 389999.9999999712;
theSat.INC                          = 12.85008005658094;
theSat.RAAN                         = 120;
theSat.AOP                          = 314.1905515359916;
theSat.TA                           = 99.88774933204925;
theSat.DryMass                      = 850;
theSat.Cd                           = 2.2;
theSat.Cr                           = 1.8;
theSat.DragArea                     = 15;
theSat.SRPArea                      = 1;
theSat.SPADDragScaleFactor          = 1;
theSat.SPADSRPScaleFactor           = 1;
theSat.NAIFId                       = -10000001;
theSat.NAIFIdReferenceFrame         = -9000001;
theSat.OrbitColor                   = Red;
theSat.TargetColor                  = Teal;
theSat.OrbitErrorCovariance         = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
theSat.CdSigma                      = 1e+70;
theSat.CrSigma                      = 1e+70;
theSat.Id                           = 'SatId';
theSat.Attitude                     = Spinner;
theSat.SPADSRPInterpolationMethod   = Bilinear;
theSat.SPADSRPScaleFactorSigma      = 1e+70;
theSat.SPADDragInterpolationMethod  = Bilinear;
theSat.SPADDragScaleFactorSigma     = 1e+70;
theSat.ModelFile                    = 'aura.3ds';
theSat.ModelOffsetX                 = 0;
theSat.ModelOffsetY                 = 0;
theSat.ModelOffsetZ                 = 0;
theSat.ModelRotationX               = 0;
theSat.ModelRotationY               = 0;
theSat.ModelRotationZ               = 90;
theSat.ModelScale                   = 0.45;
theSat.AttitudeDisplayStateType     = 'EulerAngles';
theSat.AttitudeRateDisplayStateType = 'AngularVelocity';
theSat.EulerAngleSequence           = '321';
theSat.EulerAngle1                  = 0;
theSat.EulerAngle2                  = -0;
theSat.EulerAngle3                  = 0;
theSat.AngularVelocityX             = 0;
theSat.AngularVelocityY             = 0;
theSat.AngularVelocityZ             = 0;

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft dummySat;

dummySat.DateFormat                   = TAIModJulian;
dummySat.Epoch                        = '21545';
dummySat.CoordinateSystem             = EarthMJ2000Eq;
dummySat.DisplayStateType             = Cartesian;
dummySat.X                            = 7100;
dummySat.Y                            = 0;
dummySat.Z                            = 1300;
dummySat.VX                           = 0;
dummySat.VY                           = 7.35;
dummySat.VZ                           = 1;
dummySat.DryMass                      = 850;
dummySat.Cd                           = 2.2;
dummySat.Cr                           = 1.8;
dummySat.DragArea                     = 15;
dummySat.SRPArea                      = 1;
dummySat.SPADDragScaleFactor          = 1;
dummySat.SPADSRPScaleFactor           = 1;
dummySat.NAIFId                       = -10002001;
dummySat.NAIFIdReferenceFrame         = -9002001;
dummySat.OrbitColor                   = Green;
dummySat.TargetColor                  = LightGray;
dummySat.OrbitErrorCovariance         = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
dummySat.CdSigma                      = 1e+70;
dummySat.CrSigma                      = 1e+70;
dummySat.Id                           = 'SatId';
dummySat.Attitude                     = CoordinateSystemFixed;
dummySat.SPADSRPInterpolationMethod   = Bilinear;
dummySat.SPADSRPScaleFactorSigma      = 1e+70;
dummySat.SPADDragInterpolationMethod  = Bilinear;
dummySat.SPADDragScaleFactorSigma     = 1e+70;
dummySat.ModelFile                    = 'aura.3ds';
dummySat.ModelOffsetX                 = 0;
dummySat.ModelOffsetY                 = 0;
dummySat.ModelOffsetZ                 = 0;
dummySat.ModelRotationX               = 0;
dummySat.ModelRotationY               = 0;
dummySat.ModelRotationZ               = 0;
dummySat.ModelScale                   = 1;
dummySat.AttitudeDisplayStateType     = 'Quaternion';
dummySat.AttitudeRateDisplayStateType = 'AngularVelocity';
dummySat.AttitudeCoordinateSystem     = EarthMJ2000Eq;
dummySat.EulerAngleSequence           = '321';


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft initSat;

initSat.DateFormat                   = TAIModJulian;
initSat.Epoch                        = '21545';
initSat.CoordinateSystem             = EarthMJ2000Eq;
initSat.DisplayStateType             = Cartesian;
initSat.X                            = 7100;
initSat.Y                            = 0;
initSat.Z                            = 1300;
initSat.VX                           = 0;
initSat.VY                           = 7.35;
initSat.VZ                           = 1;
initSat.DryMass                      = 850;
initSat.Cd                           = 2.2;
initSat.Cr                           = 1.8;
initSat.DragArea                     = 15;
initSat.SRPArea                      = 1;
initSat.SPADDragScaleFactor          = 1;
initSat.SPADSRPScaleFactor           = 1;
initSat.NAIFId                       = -10010001;
initSat.NAIFIdReferenceFrame         = -9010001;
initSat.OrbitColor                   = Green;
initSat.TargetColor                  = LightGray;
initSat.OrbitErrorCovariance         = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
initSat.CdSigma                      = 1e+70;
initSat.CrSigma                      = 1e+70;
initSat.Id                           = 'SatId';
initSat.Attitude                     = CoordinateSystemFixed;
initSat.SPADSRPInterpolationMethod   = Bilinear;
initSat.SPADSRPScaleFactorSigma      = 1e+70;
initSat.SPADDragInterpolationMethod  = Bilinear;
initSat.SPADDragScaleFactorSigma     = 1e+70;
initSat.ModelFile                    = 'aura.3ds';
initSat.ModelOffsetX                 = 0;
initSat.ModelOffsetY                 = 0;
initSat.ModelOffsetZ                 = 0;
initSat.ModelRotationX               = 0;
initSat.ModelRotationY               = 0;
initSat.ModelRotationZ               = 0;
initSat.ModelScale                   = 1;
initSat.AttitudeDisplayStateType     = 'Quaternion';
initSat.AttitudeRateDisplayStateType = 'AngularVelocity';
initSat.AttitudeCoordinateSystem     = EarthMJ2000Eq;
initSat.EulerAngleSequence           = '321';


%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel SimProp_ForceModel;

SimProp_ForceModel.CentralBody                      = Earth;
SimProp_ForceModel.PrimaryBodies                    = {Earth};
SimProp_ForceModel.Drag                             = None;
SimProp_ForceModel.SRP                              = Off;
SimProp_ForceModel.RelativisticCorrection           = Off;
SimProp_ForceModel.ErrorControl                     = RSSStep;
SimProp_ForceModel.GravityField.Earth.Degree        = 4;
SimProp_ForceModel.GravityField.Earth.Order         = 4;
SimProp_ForceModel.GravityField.Earth.StmLimit      = 100;
SimProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
SimProp_ForceModel.GravityField.Earth.TideModel     = 'None';


Create ForceModel RealTimeProp_ForceModel;

RealTimeProp_ForceModel.CentralBody                      = Earth;
RealTimeProp_ForceModel.PrimaryBodies                    = {Earth};
RealTimeProp_ForceModel.Drag                             = None;
RealTimeProp_ForceModel.SRP                              = Off;
RealTimeProp_ForceModel.RelativisticCorrection           = Off;
RealTimeProp_ForceModel.ErrorControl                     = RSSStep;
RealTimeProp_ForceModel.GravityField.Earth.Degree        = 4;
RealTimeProp_ForceModel.GravityField.Earth.Order         = 4;
RealTimeProp_ForceModel.GravityField.Earth.StmLimit      = 100;
RealTimeProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
RealTimeProp_ForceModel.GravityField.Earth.TideModel     = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator SimProp;

SimProp.FM                       = SimProp_ForceModel;
SimProp.Type                     = RungeKutta89;
SimProp.InitialStepSize          = 60;
SimProp.Accuracy                 = 9.999999999999999e-12;
SimProp.MinStep                  = 0.001;
SimProp.MaxStep                  = 60;
SimProp.MaxStepAttempts          = 50;
SimProp.StopIfAccuracyIsViolated = true;


Create Propagator RealTimeProp;

RealTimeProp.FM                       = RealTimeProp_ForceModel;
RealTimeProp.Type                     = RungeKutta89;
RealTimeProp.InitialStepSize          = 60;
RealTimeProp.Accuracy                 = 9.999999999999999e-12;
RealTimeProp.MinStep                  = 0.001;
RealTimeProp.MaxStep                  = 0.1;
RealTimeProp.MaxStepAttempts          = 50;
RealTimeProp.StopIfAccuracyIsViolated = true;


%----------------------------------------
%---------- Coordinate Systems
%----------------------------------------

Create CoordinateSystem EarthMoonRot;

EarthMoonRot.Origin    = Earth;
EarthMoonRot.Axes      = ObjectReferenced;
EarthMoonRot.XAxis     = R;
EarthMoonRot.ZAxis     = N;
EarthMoonRot.Primary   = Earth;
EarthMoonRot.Secondary = Luna;


Create CoordinateSystem VNB;

VNB.Origin    = theSat;
VNB.Axes      = ObjectReferenced;
VNB.XAxis     = V;
VNB.YAxis     = N;
VNB.Primary   = Earth;
VNB.Secondary = theSat;


Create CoordinateSystem SatFixed;

SatFixed.Origin = theSat;
SatFixed.Axes   = BodyFixed;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create GroundTrackPlot EarthGroundTrack;

EarthGroundTrack.SolverIterations     = Current;
EarthGroundTrack.UpperLeft            = [ 0.1541176470588235 0.4202380952380952 ];
EarthGroundTrack.Size                 = [ 0.3517647058823529 0.4035714285714286 ];
EarthGroundTrack.RelativeZOrder       = 5;
EarthGroundTrack.Maximized            = false;
EarthGroundTrack.Add                  = {theSat};
EarthGroundTrack.DataCollectFrequency = 10;
EarthGroundTrack.UpdatePlotFrequency  = 50;
EarthGroundTrack.NumPointsToRedraw    = 0;
EarthGroundTrack.ShowPlot             = true;
EarthGroundTrack.MaxPlotPoints        = 20000;
EarthGroundTrack.CentralBody          = Earth;
EarthGroundTrack.TextureMap           = 'ModifiedBlueMarble.jpg';


Create GroundTrackPlot MoonGroundTrack;

MoonGroundTrack.SolverIterations     = Current;
MoonGroundTrack.UpperLeft            = [ 0.51 0.4202380952380952 ];
MoonGroundTrack.Size                 = [ 0.3594117647058824 0.405952380952381 ];
MoonGroundTrack.RelativeZOrder       = 10;
MoonGroundTrack.Maximized            = false;
MoonGroundTrack.Add                  = {theSat};
MoonGroundTrack.DataCollectFrequency = 10;
MoonGroundTrack.UpdatePlotFrequency  = 50;
MoonGroundTrack.NumPointsToRedraw    = 0;
MoonGroundTrack.ShowPlot             = true;
MoonGroundTrack.MaxPlotPoints        = 20000;
MoonGroundTrack.CentralBody          = Luna;
MoonGroundTrack.TextureMap           = 'Moon_HermesCelestiaMotherlode.jpg';


Create DynamicDataDisplay DynamicDataDisplay;

DynamicDataDisplay.UpperLeft      = [ 0.1305882352941176 0.844047619047619 ];
DynamicDataDisplay.Size           = [ 0.8358823529411765 0.7547619047619047 ];
DynamicDataDisplay.RelativeZOrder = 15;
DynamicDataDisplay.Maximized      = false;
DynamicDataDisplay.AddParameters  = {1, theSat.UTCGregorian, theSat.EulerAngle1, theSat.EulerAngle2, theSat.EulerAngle3};
DynamicDataDisplay.RowTextColors  = {1, [0 0 0], [0 0 0], [0 0 0], [0 0 0]};
DynamicDataDisplay.WarnColor      = [218 165 32];
DynamicDataDisplay.CritColor      = [255 0 0];


Create ReportFile ReportFile;

ReportFile.SolverIterations = Current;
ReportFile.UpperLeft        = [ 0 0 ];
ReportFile.Size             = [ 0 0 ];
ReportFile.RelativeZOrder   = 0;
ReportFile.Maximized        = false;
ReportFile.Filename         = 'MOCReport.txt';
ReportFile.Precision        = 16;
ReportFile.WriteHeaders     = true;
ReportFile.LeftJustify      = On;
ReportFile.ZeroFill         = Off;
ReportFile.FixedWidth       = true;
ReportFile.Delimiter        = ' ';
ReportFile.ColumnWidth      = 23;
ReportFile.WriteReport      = true;


%----------------------------------------
%---------- Gpen Frames Objects
%----------------------------------------
Create OpenFramesInterface OFI_Inertial;

OFI_Inertial.SolverIterations        = Current;
OFI_Inertial.UpperLeft               = [ 0.003529411764705882 0 ];
OFI_Inertial.Size                    = [ 0.2905882352941176 0.4035714285714286 ];
OFI_Inertial.RelativeZOrder          = 28;
OFI_Inertial.Maximized               = false;
OFI_Inertial.Add                     = {theSat, Earth, Sun};
OFI_Inertial.View                    = {InertialView, SatToEarthView, SatToSunView};
OFI_Inertial.CoordinateSystem        = EarthMJ2000Eq;
OFI_Inertial.DrawObject              = [ true true true ];
OFI_Inertial.DrawTrajectory          = [ true true true ];
OFI_Inertial.DrawAxes                = [ false false false ];
OFI_Inertial.DrawXYPlane             = [ false false false ];
OFI_Inertial.DrawLabel               = [ true true true ];
OFI_Inertial.DrawUsePropLabel        = [ false false false ];
OFI_Inertial.DrawCenterPoint         = [ true true false ];
OFI_Inertial.DrawEndPoints           = [ true true false ];
OFI_Inertial.DrawVelocity            = [ false false false ];
OFI_Inertial.DrawGrid                = [ false false false ];
OFI_Inertial.DrawLineWidth           = [ 2 2 2 ];
OFI_Inertial.DrawMarkerSize          = [ 10 10 1 ];
OFI_Inertial.DrawFontSize            = [ 14 14 14 ];
OFI_Inertial.Axes                    = Off;
OFI_Inertial.AxesLength              = 1;
OFI_Inertial.AxesLabels              = On;
OFI_Inertial.FrameLabel              = Off;
OFI_Inertial.XYPlane                 = Off;
OFI_Inertial.EclipticPlane           = Off;
OFI_Inertial.EnableStars             = On;
OFI_Inertial.StarCatalog             = 'inp_StarsHYGv3.txt';
OFI_Inertial.StarCount               = 7000;
OFI_Inertial.MinStarMag              = -2;
OFI_Inertial.MaxStarMag              = 8;
OFI_Inertial.MinStarPixels           = 1;
OFI_Inertial.MaxStarPixels           = 10;
OFI_Inertial.MinStarDimRatio         = 0.800000011920929;
OFI_Inertial.ShowPlot                = true;
OFI_Inertial.ShowToolbar             = true;
OFI_Inertial.SolverIterLastN         = 1;
OFI_Inertial.ShowVR                  = false;
OFI_Inertial.PlaybackTimeScale       = 32;
OFI_Inertial.MultisampleAntiAliasing = On;
OFI_Inertial.MSAASamples             = 2;
OFI_Inertial.DrawFontPosition        = {'Top-Right', 'Top-Right', 'Top-Right'};


Create OpenFramesInterface OFI_EarthMoonRot;

OFI_EarthMoonRot.SolverIterations        = Current;
OFI_EarthMoonRot.UpperLeft               = [ 0.6 0 ];
OFI_EarthMoonRot.Size                    = [ 0.2935294117647059 0.405952380952381 ];
OFI_EarthMoonRot.RelativeZOrder          = 18;
OFI_EarthMoonRot.Maximized               = false;
OFI_EarthMoonRot.Add                     = {theSat, Earth, Luna};
OFI_EarthMoonRot.View                    = {EMRotatingView, SatView};
OFI_EarthMoonRot.CoordinateSystem        = EarthMoonRot;
OFI_EarthMoonRot.DrawObject              = [ true true true ];
OFI_EarthMoonRot.DrawTrajectory          = [ true true true ];
OFI_EarthMoonRot.DrawAxes                = [ true false false ];
OFI_EarthMoonRot.DrawXYPlane             = [ false false false ];
OFI_EarthMoonRot.DrawLabel               = [ true true true ];
OFI_EarthMoonRot.DrawUsePropLabel        = [ false false false ];
OFI_EarthMoonRot.DrawCenterPoint         = [ true true true ];
OFI_EarthMoonRot.DrawEndPoints           = [ true true true ];
OFI_EarthMoonRot.DrawVelocity            = [ false false false ];
OFI_EarthMoonRot.DrawGrid                = [ false false false ];
OFI_EarthMoonRot.DrawLineWidth           = [ 2 2 2 ];
OFI_EarthMoonRot.DrawMarkerSize          = [ 10 10 10 ];
OFI_EarthMoonRot.DrawFontSize            = [ 14 14 14 ];
OFI_EarthMoonRot.Axes                    = Off;
OFI_EarthMoonRot.AxesLength              = 1;
OFI_EarthMoonRot.AxesLabels              = On;
OFI_EarthMoonRot.FrameLabel              = Off;
OFI_EarthMoonRot.XYPlane                 = Off;
OFI_EarthMoonRot.EclipticPlane           = Off;
OFI_EarthMoonRot.EnableStars             = On;
OFI_EarthMoonRot.StarCatalog             = 'inp_StarsHYGv3.txt';
OFI_EarthMoonRot.StarCount               = 40000;
OFI_EarthMoonRot.MinStarMag              = -2;
OFI_EarthMoonRot.MaxStarMag              = 6;
OFI_EarthMoonRot.MinStarPixels           = 1;
OFI_EarthMoonRot.MaxStarPixels           = 10;
OFI_EarthMoonRot.MinStarDimRatio         = 0.5;
OFI_EarthMoonRot.ShowPlot                = true;
OFI_EarthMoonRot.ShowToolbar             = true;
OFI_EarthMoonRot.SolverIterLastN         = 1;
OFI_EarthMoonRot.ShowVR                  = false;
OFI_EarthMoonRot.PlaybackTimeScale       = 32;
OFI_EarthMoonRot.MultisampleAntiAliasing = On;
OFI_EarthMoonRot.MSAASamples             = 2;
OFI_EarthMoonRot.DrawFontPosition        = {'Top-Right', 'Top-Right', 'Top-Right'};


%  TODO:  this should be in spacecraft body coords.  
%  the same way the OrbitView named SpacecraftView is configured.
Create OpenFramesInterface OFI_VNB;

OFI_VNB.SolverIterations        = Current;
OFI_VNB.UpperLeft               = [ 0.2976470588235294 0 ];
OFI_VNB.Size                    = [ 0.2952941176470588 0.405952380952381 ];
OFI_VNB.RelativeZOrder          = 29;
OFI_VNB.Maximized               = false;
OFI_VNB.Add                     = {theSat, Earth, Luna, Sun};
OFI_VNB.View                    = {SatToEarthView, VNBView};
OFI_VNB.Vector                  = {SunVector};
OFI_VNB.CoordinateSystem        = VNB;
OFI_VNB.DrawObject              = [ true true true true ];
OFI_VNB.DrawTrajectory          = [ true true true true ];
OFI_VNB.DrawAxes                = [ false false false false ];
OFI_VNB.DrawXYPlane             = [ false false false false ];
OFI_VNB.DrawLabel               = [ true true true true ];
OFI_VNB.DrawUsePropLabel        = [ false false false false ];
OFI_VNB.DrawCenterPoint         = [ true true false false ];
OFI_VNB.DrawEndPoints           = [ true true false false ];
OFI_VNB.DrawVelocity            = [ false false false false ];
OFI_VNB.DrawGrid                = [ false false false false ];
OFI_VNB.DrawLineWidth           = [ 2 2 2 2 ];
OFI_VNB.DrawMarkerSize          = [ 10 10 1 1 ];
OFI_VNB.DrawFontSize            = [ 14 14 14 14 ];
OFI_VNB.Axes                    = On;
OFI_VNB.AxesLength              = 1;
OFI_VNB.AxesLabels              = On;
OFI_VNB.FrameLabel              = Off;
OFI_VNB.XYPlane                 = Off;
OFI_VNB.EclipticPlane           = Off;
OFI_VNB.EnableStars             = On;
OFI_VNB.StarCatalog             = 'inp_StarsHYGv3.txt';
OFI_VNB.StarCount               = 40000;
OFI_VNB.MinStarMag              = -2;
OFI_VNB.MaxStarMag              = 6;
OFI_VNB.MinStarPixels           = 1;
OFI_VNB.MaxStarPixels           = 10;
OFI_VNB.MinStarDimRatio         = 0.5;
OFI_VNB.ShowPlot                = true;
OFI_VNB.ShowToolbar             = true;
OFI_VNB.SolverIterLastN         = 1;
OFI_VNB.ShowVR                  = false;
OFI_VNB.PlaybackTimeScale       = 4096;
OFI_VNB.MultisampleAntiAliasing = On;
OFI_VNB.MSAASamples             = 2;
OFI_VNB.DrawFontPosition        = {'Top-Right', 'Top-Right', 'Top-Right', 'Top-Right'};

%----------------------------------------
%---------- Arrays, Variables, Strings
%----------------------------------------
Create Variable pauseDuration totalMissionTime totalPropTime;
Create String systemTimeString;
totalPropTime = 0.5;

%----------------------------------------
%---------- User Objects
%----------------------------------------

Create OpenFramesView InertialView;

InertialView.ViewFrame            = CoordinateSystem;
InertialView.ViewTrajectory       = Off;
InertialView.InertialFrame        = On;
InertialView.SetDefaultLocation   = On;
InertialView.DefaultEye           = [ 30000 0 0 ];
InertialView.DefaultCenter        = [ 0 0 0 ];
InertialView.DefaultUp            = [ 0 0 1 ];
InertialView.SetCurrentLocation   = On;
InertialView.CurrentEye           = [ -28253.32318972786 -777.7050099454879 10057.08226347447 ];
InertialView.CurrentCenter        = [ -7.275957614183426e-12 3.069544618483633e-12 0 ];
InertialView.CurrentUp            = [ 0.33083702660161 0.1065228180210172 0.9376565208381302 ];
InertialView.FOVy                 = 45;


Create OpenFramesView EMRotatingView;

EMRotatingView.ViewFrame          = CoordinateSystem;
EMRotatingView.ViewTrajectory     = Off;
EMRotatingView.InertialFrame      = Off;
EMRotatingView.SetDefaultLocation = On;
EMRotatingView.DefaultEye         = [ 200000 0 500000 ];
EMRotatingView.DefaultCenter      = [ 200000 0 0 ];
EMRotatingView.DefaultUp          = [ 0 1 0 ];
EMRotatingView.SetCurrentLocation = Off;
EMRotatingView.FOVy                                                                                                                                                                         = 45;


Create OpenFramesView SatView;

SatView.ViewFrame          = theSat;
SatView.ViewTrajectory     = Off;
SatView.InertialFrame      = On;
SatView.SetDefaultLocation = On;
SatView.DefaultEye         = [ 0 -1 0 ];
SatView.DefaultCenter      = [ 0 0 0 ];
SatView.DefaultUp          = [ 0 0 1 ];
SatView.SetCurrentLocation = On;
SatView.CurrentEye         = [ -27346.28140861249 -290922.4996747191 294602.4645004478 ];
SatView.CurrentCenter      = [ 3.637978807091713e-12 1.164153218269348e-10 1.164153218269348e-10 ];
SatView.CurrentUp          = [ -0.01600030787808049 0.7121878896481082 0.7018065260357591 ];
SatView.FOVy               = 45;


Create OpenFramesView VNBView;

VNBView.ViewFrame          = CoordinateSystem;
VNBView.ViewTrajectory     = Off;
VNBView.InertialFrame      = Off;
VNBView.SetDefaultLocation = On;
VNBView.DefaultEye         = [ 0 0 50000 ];
VNBView.DefaultCenter      = [ 0 0 0 ];
VNBView.DefaultUp          = [ 1 0 0 ];
VNBView.SetCurrentLocation = Off;
VNBView.FOVy               = 45;


Create OpenFramesView SatToEarthView;

SatToEarthView.ViewFrame          = theSat;
SatToEarthView.ViewTrajectory     = Off;
SatToEarthView.InertialFrame      = On;
SatToEarthView.LookAtFrame        = Earth;
SatToEarthView.ShortestAngle      = Off;
SatToEarthView.SetDefaultLocation = On;
SatToEarthView.DefaultEye         = [ 96.26489695398367 -327.332770274532 234.1989265212196 ];
SatToEarthView.DefaultCenter      = [ -5.684341886080801e-14 0 2.842170943040401e-14 ];
SatToEarthView.DefaultUp          = [ -0.3856878144458252 0.4591466959875297 0.8002682183816483 ];
SatToEarthView.SetCurrentLocation = On;
SatToEarthView.CurrentEye         = [ 96.26489695398364 -327.332770274532 234.1989265212196 ];
SatToEarthView.CurrentCenter      = [ -8.526512829121202e-14 0 2.842170943040401e-14 ];
SatToEarthView.CurrentUp          = [ -0.3856878144458252 0.4591466959875297 0.8002682183816483 ];
SatToEarthView.FOVy               = 45;


Create OpenFramesView SatToSunView;

SatToSunView.ViewFrame          = theSat;
SatToSunView.ViewTrajectory     = Off;
SatToSunView.InertialFrame      = On;
SatToSunView.LookAtFrame        = Sun;
SatToSunView.ShortestAngle      = Off;
SatToSunView.SetDefaultLocation = On;
SatToSunView.DefaultEye         = [ 72.74819685927726 -404.8014044071918 45.89480263103095 ];
SatToSunView.DefaultCenter      = [ 1.4210854715202e-14 0 4.263256414560601e-14 ];
SatToSunView.DefaultUp          = [ 0.01155930676636818 0.1146976006048337 0.993333198298826 ];
SatToSunView.SetCurrentLocation = Off;
SatToSunView.FOVy               = 45;


Create OpenFramesVector SunVector;

SunVector.VectorColor           = [255 255 0];
SunVector.SourceObject          = theSat;
SunVector.VectorType            = Relative Position;
SunVector.DestinationObject     = Sun;
SunVector.VectorLabel           = 'Sun';
SunVector.VectorLengthType      = 'Auto';

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
BeginMissionSequence;

pauseDuration    = 0.05;
totalMissionTime = 0.0001;
totalPropTime    = 0.5;

% Set epoch of spacecraft to current wall-clock time
[systemTimeString]          = SystemTime('UTCGregorian');
dummySat.Epoch.UTCGregorian = systemTimeString;  % NOTE: we should be able to use str2num but there is a blocker bug.
theSat.TAIModJulian         = dummySat.TAIModJulian;

%  Propagate the entire mission
initSat = theSat;
Propagate SimProp(theSat) {theSat.ElapsedDays = totalPropTime};
theSat  = initSat;

While theSat.ElapsedDays <= totalMissionTime
   
   % Pause for requested duration
   Pause(pauseDuration);
   
   % Get the current system time
   [systemTimeString]         = SystemTime('UTCGregorian');
   initSat.Epoch.UTCGregorian = systemTimeString;  % NOTE: we should be able to use str2num but there is a blocker bug.
   
   % Set attitude using crude spinning model
   % In a MOC this could come from a Python script that polls a server
   % Note that the EulerAngle sequence is defined using "EulerAngleSequence"
   % on the spacecraft.
   theSat.EulerAngle1 = theSat.ElapsedSecs/10;
   theSat.EulerAngle2 = theSat.ElapsedSecs/10;
   theSat.EulerAngle3 = theSat.ElapsedSecs/10;
   
   % Get the current system time again in the event that getting attitude took 
   % a non-neglible amount of time
   [systemTimeString]         = SystemTime('UTCGregorian');
   initSat.Epoch.UTCGregorian = systemTimeString;  % NOTE: we should be able to use str2num but there is a blocker bug.
   
   % Propagate to the current system time
   Propagate SimProp(theSat) {theSat.TAIModJulian = initSat.TAIModJulian};
   
   Report ReportFile theSat.TAIModJulian initSat.TAIModJulian initSat.UTCGregorian theSat.EulerAngle1 theSat.EulerAngle2 theSat.EulerAngle3;
   
   UpdateDynamicData DynamicDataDisplay;
EndWhile;
