%
%  Ex_OFI_CustomSegmentColors
%
%  Specify different colors for different trajectory segments in 3-D views.
%  This script demonstrates how to target a Hohmann Transfer
%
%  Released: R2020a
%


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;

DefaultSC.DateFormat                   = TAIModJulian;
DefaultSC.Epoch                        = '21545';
DefaultSC.CoordinateSystem             = EarthMJ2000Eq;
DefaultSC.DisplayStateType             = Cartesian;
DefaultSC.X                            = 7100;
DefaultSC.Y                            = 0;
DefaultSC.Z                            = 1300;
DefaultSC.VX                           = 0;
DefaultSC.VY                           = 7.35;
DefaultSC.VZ                           = 1;
DefaultSC.DryMass                      = 850;
DefaultSC.Cd                           = 2.2;
DefaultSC.Cr                           = 1.8;
DefaultSC.DragArea                     = 15;
DefaultSC.SRPArea                      = 1;
DefaultSC.SPADDragScaleFactor          = 1;
DefaultSC.SPADSRPScaleFactor           = 1;
DefaultSC.NAIFId                       = -10003001;
DefaultSC.NAIFIdReferenceFrame         = -9003001;
DefaultSC.OrbitColor                   = Red;
DefaultSC.TargetColor                  = Teal;
DefaultSC.OrbitErrorCovariance         = [ 1e+070 0 0 0 0 0 ; 0 1e+070 0 0 0 0 ; 0 0 1e+070 0 0 0 ; 0 0 0 1e+070 0 0 ; 0 0 0 0 1e+070 0 ; 0 0 0 0 0 1e+070 ];
DefaultSC.CdSigma                      = 1e+070;
DefaultSC.CrSigma                      = 1e+070;
DefaultSC.Id                           = 'SatId';
DefaultSC.Attitude                     = CoordinateSystemFixed;
DefaultSC.SPADSRPInterpolationMethod   = Bilinear;
DefaultSC.SPADSRPScaleFactorSigma      = 1e+070;
DefaultSC.SPADDragInterpolationMethod  = Bilinear;
DefaultSC.SPADDragScaleFactorSigma     = 1e+070;
DefaultSC.ModelFile                    = 'aura.3ds';
DefaultSC.ModelOffsetX                 = 0;
DefaultSC.ModelOffsetY                 = 0;
DefaultSC.ModelOffsetZ                 = 0;
DefaultSC.ModelRotationX               = 0;
DefaultSC.ModelRotationY               = 0;
DefaultSC.ModelRotationZ               = 0;
DefaultSC.ModelScale                   = 1;
DefaultSC.AttitudeDisplayStateType     = 'Quaternion';
DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
DefaultSC.AttitudeCoordinateSystem     = EarthMJ2000Eq;
DefaultSC.EulerAngleSequence           = '321';


%----------------------------------------
%---------- Propagators
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;

DefaultProp_ForceModel.CentralBody                      = Earth;
DefaultProp_ForceModel.PrimaryBodies                    = {Earth};
DefaultProp_ForceModel.Drag                             = None;
DefaultProp_ForceModel.SRP                              = Off;
DefaultProp_ForceModel.RelativisticCorrection           = Off;
DefaultProp_ForceModel.ErrorControl                     = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree        = 4;
DefaultProp_ForceModel.GravityField.Earth.Order         = 4;
DefaultProp_ForceModel.GravityField.Earth.StmLimit      = 100;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.TideModel     = 'None';


%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;

DefaultProp.FM                       = DefaultProp_ForceModel;
DefaultProp.Type                     = RungeKutta89;
DefaultProp.InitialStepSize          = 60;
DefaultProp.Accuracy                 = 9.999999999999999e-012;
DefaultProp.MinStep                  = 0.001;
DefaultProp.MaxStep                  = 2700;
DefaultProp.MaxStepAttempts          = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn TOI;

TOI.CoordinateSystem   = Local;
TOI.Origin             = Earth;
TOI.Axes               = VNB;
TOI.Element1           = 0;
TOI.Element2           = 0;
TOI.Element3           = 0;
TOI.DecrementMass      = false;
TOI.Isp                = 300;
TOI.GravitationalAccel = 9.810000000000001;

Create ImpulsiveBurn GOI;

GOI.CoordinateSystem   = Local;
GOI.Origin             = Earth;
GOI.Axes               = VNB;
GOI.Element1           = 0;
GOI.Element2           = 0;
GOI.Element3           = 0;
GOI.DecrementMass      = false;
GOI.Isp                = 300;
GOI.GravitationalAccel = 9.810000000000001;

%----------------------------------------
%---------- Solvers
%----------------------------------------

Create DifferentialCorrector DC;

DC.ShowProgress      = true;
DC.ReportStyle       = Normal;
DC.ReportFile        = 'DifferentialCorrectorDC.data';
DC.MaximumIterations = 25;
DC.DerivativeMethod  = ForwardDifference;
DC.Algorithm         = NewtonRaphson;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OpenFramesInterface OpenFrames1;

OpenFrames1.SolverIterations        = Current;
OpenFrames1.UpperLeft               = [ 0 0 ];
OpenFrames1.Size                    = [ 0.4978567054500919 0.9939320388349514 ];
OpenFrames1.RelativeZOrder          = 222;
OpenFrames1.Maximized               = false;
OpenFrames1.Add                     = {DefaultSC, Earth, Sun};
OpenFrames1.View                    = {CoordinateSystemView1, EarthView1, DefaultSCView1};
OpenFrames1.CoordinateSystem        = EarthMJ2000Eq;
OpenFrames1.DrawObject              = [ true true false ];
OpenFrames1.DrawTrajectory          = [ true true false ];
OpenFrames1.DrawAxes                = [ false false false ];
OpenFrames1.DrawXYPlane             = [ false false false ];
OpenFrames1.DrawLabel               = [ true true false ];
OpenFrames1.DrawUsePropLabel        = [ false false false ];
OpenFrames1.DrawCenterPoint         = [ true true false ];
OpenFrames1.DrawEndPoints           = [ true true false ];
OpenFrames1.DrawVelocity            = [ false false false ];
OpenFrames1.DrawGrid                = [ false false false ];
OpenFrames1.DrawLineWidth           = [ 2 2 2 ];
OpenFrames1.DrawMarkerSize          = [ 10 10 10 ];
OpenFrames1.DrawFontSize            = [ 14 14 14 ];
OpenFrames1.Axes                    = On;
OpenFrames1.AxesLength              = 1;
OpenFrames1.AxesLabels              = On;
OpenFrames1.FrameLabel              = Off;
OpenFrames1.XYPlane                 = On;
OpenFrames1.EclipticPlane           = Off;
OpenFrames1.EnableStars             = On;
OpenFrames1.StarCatalog             = 'inp_StarsHYGv3.txt';
OpenFrames1.StarCount               = 40000;
OpenFrames1.MinStarMag              = -2;
OpenFrames1.MaxStarMag              = 6;
OpenFrames1.MinStarPixels           = 1;
OpenFrames1.MaxStarPixels           = 10;
OpenFrames1.MinStarDimRatio         = 0.5;
OpenFrames1.ShowPlot                = true;
OpenFrames1.ShowToolbar             = true;
OpenFrames1.SolverIterLastN         = 1;
OpenFrames1.ShowVR                  = false;
OpenFrames1.PlaybackTimeScale       = 3600;
OpenFrames1.MultisampleAntiAliasing = On;
OpenFrames1.MSAASamples             = 2;
OpenFrames1.DrawFontPosition        = {'Top-Right', 'Top-Right', 'Top-Right'};

%----------------------------------------
%---------- User Objects
%----------------------------------------

Create OpenFramesView CoordinateSystemView1;

CoordinateSystemView1.ViewFrame          = CoordinateSystem;
CoordinateSystemView1.ViewTrajectory     = Off;
CoordinateSystemView1.InertialFrame      = Off;
CoordinateSystemView1.SetDefaultLocation = On;
CoordinateSystemView1.DefaultEye         = [ 335.78274069 -1543.63919451 118501.88910654 ];
CoordinateSystemView1.DefaultCenter      = [ 0 0 0 ];
CoordinateSystemView1.DefaultUp          = [ 0.99991256 -0.0128788 -0.00300108 ];
CoordinateSystemView1.SetCurrentLocation = On;
CoordinateSystemView1.CurrentEye         = [ 335.7827406916811 -1543.63919451052 118501.8891065422 ];
CoordinateSystemView1.CurrentCenter      = [ 2.842170943040401e-13 -4.547473508864641e-13 1.455191522836685e-11 ];
CoordinateSystemView1.CurrentUp          = [ 0.9999125612384814 -0.01287879649157642 -0.003001079543866816 ];
CoordinateSystemView1.FOVy = 45;

Create OpenFramesView EarthView1;

EarthView1.ViewFrame              = Earth;
EarthView1.ViewTrajectory         = Off;
EarthView1.InertialFrame          = Off;
EarthView1.SetDefaultLocation     = Off;
EarthView1.SetCurrentLocation     = Off;
EarthView1.FOVy                   = 45;

Create OpenFramesView DefaultSCView1;

DefaultSCView1.ViewFrame          = DefaultSC;
DefaultSCView1.ViewTrajectory     = Off;
DefaultSCView1.InertialFrame      = Off;
DefaultSCView1.SetDefaultLocation = Off;
DefaultSCView1.SetCurrentLocation = Off;
DefaultSCView1.FOVy               = 45;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
BeginMissionSequence;

DefaultSC.OrbitColor = 'Yellow';
Propagate 'Prop to Perigee' DefaultProp(DefaultSC) {DefaultSC.Periapsis};

% Burn in the velocity direction to reach an alternate Apoapsis point
Target 'Raise and Circularize' DC {SolveMode = Solve, ExitMode = DiscardAndContinue, ShowProgressWindow = true};
   Vary 'Vary TOI.V' DC(TOI.Element1 = 0.5, {Perturbation = 0.0001, Lower = 0, Upper = 3.14159, MaxStep = 0.2, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Maneuver 'Apply TOI' TOI(DefaultSC);
   Propagate 'Prop to Apogee' DefaultProp(DefaultSC) {DefaultSC.Apoapsis, OrbitColor = [255 0 0]};
   Achieve 'Achieve RMAG' DC(DefaultSC.Earth.RMAG = 42165, {Tolerance = 0.1});
   Vary 'Vary GOI.V' DC(GOI.Element1 = 0.5, {Perturbation = 0.0001, Lower = 0, Upper = 3.14159, MaxStep = 0.2, AdditiveScaleFactor = 0.0, MultiplicativeScaleFactor = 1.0});
   Maneuver 'Apply GOI' GOI(DefaultSC);
   Achieve 'Achieve ECC' DC(DefaultSC.ECC = 0, {Tolerance = 0.1});
EndTarget;  % For targeter DC
DefaultSC.OrbitColor = 'Blue';
Propagate 'Prop 1 Day' DefaultProp(DefaultSC) {DefaultSC.ElapsedSecs = 86400};
